### ISSUE TITLE
'/' character problems in console

### ISSUE THREAD

**Issue by ObaniGemini** [GrangerHub/tremulous#8]
The character `/` isn't always assimilated as `\` when doing a command.

From what I observed, it seems like it works with built-in commands, but not the ones added by the server.
For example `/name X` **is** properly converted to `\name X`, but `/donate X` **isn't** converted to `\donate X` and does not lead to any error message in the console.
From what I know, `\donate` isn't a built-in command, while `\callvote` is. Am I right ?

I didn't gave much more trials, just a simple report and what I think could be the origin.
Tested it on "test" server.

**Comment by wtfbbqhax** [comment]
`donate` and `callvote` are both provided by the game, neither are built in. 

Can you please provide a screenshot of the command your typing, and another for the result you're seeing.

**Comment by ObaniGemini** [comment]
no screenshot is needed for a text file.
I typed `/donate 5` and it didn't return me anything (blank)

**Comment by wtfbbqhax** [comment]
Closing this since I am pretty sure its invalid and or fixed.

**Comment by ObaniGemini** [comment]
nice reason. Did you just test ?

**Comment by dGr8LookinSparky** [comment]
On the test7341 server `donate` does tab complete (and convert `/` to `\`), but when testing it on a 1.1 based QVM like multiprotocol slackers that the GrangerPub server uses, it doesn't tab complete nor convert `/` to `\`, so it seems to be QVM specific, that is it looks like tab completion for any command defined in the game QVM that is gpp or newer would tab complete, include admin commands (this also applies to other "custom" commands like `teamstatus` and `share` ).  However, while tab completion is certainly useful, I don't think that conversion from `/` to `\` is necessary since from my experience enter a command that begins with `/` has always worked for me on the alpha release client, that is it is recognized as a command.
